// src/components/NotesGrid.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import NoteCard from './NoteCard.svelte';
  import type { Note, UpdateNoteData } from '../lib/types';
  
  export let notes: Note[];
  export let loading = false;
  
  const dispatch = createEventDispatcher<{
    update: { id: string; data: UpdateNoteData };
    delete: string;
  }>();
  
  function handleUpdate(event: CustomEvent<{ id: string; data: UpdateNoteData }>) {
    dispatch('update', event.detail);
  }
  
  function handleDelete(event: CustomEvent<string>) {
    dispatch('delete', event.detail);
  }
</script>

{#if notes.length === 0}
  <div class="text-center py-16 animate-fade-in">
    <div class="text-7xl mb-6">📝</div>
    <h3 class="text-xl font-semibold mb-3 text-foreground-DEFAULT dark:text-foreground-dark">
      No notes found
    </h3>
    <p class="text-muted-foreground-DEFAULT dark:text-muted-foreground-dark text-lg">
      Create your first note to get started!
    </p>
  </div>
{:else}
  <div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
    {#each notes as note (note.id)}
      <div class="animate-fade-in">
        <NoteCard
          {note}
          {loading}
          on:update={handleUpdate}
          on:delete={handleDelete}
        />
      </div>
    {/each}
  </div>
{/if}

// src/components/notes-grid.tsx
import { Note, UpdateNoteData } from '@/types/note'
import { NoteCard } from './note-card'

interface NotesGridProps {
  notes: Note[]
  onUpdate: (id: string, data: UpdateNoteData) => Promise<void>
  onDelete: (id: string) => Promise<void>
  loading?: boolean
}

export function NotesGrid({ notes, onUpdate, onDelete, loading }: NotesGridProps) {
  if (notes.length === 0) {
    return (
      <div className="text-center py-12">
        <div className="text-6xl mb-4">📝</div>
        <h3 className="text-lg font-semibold mb-2">No notes yet</h3>
        <p className="text-muted-foreground">
          Create your first note to get started!
        </p>
      </div>
    )
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {notes.map((note) => (
        <NoteCard
          key={note.id}
          note={note}
          onUpdate={onUpdate}
          onDelete={onDelete}
          loading={loading}
        />
      ))}
    </div>
  )
}
